### Get all blogs
GET http://localhost:3003/api/blogs
Accept: application/json

### Get a single blog by ID
GET http://localhost:3003/api/blogs/67c49be4cec3762f308ec81e
Accept: application/json

### Create a new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1c2luZW4iLCJpZCI6IjY3ZDNlZGU4ZTk2MDI5YmM5ZmU2ZDVjNyIsImlhdCI6MTc0MzM1NjQ0MywiZXhwIjoxNzQzMzYwMDQzfQ.u2v9KTZJHF6s8jtzDH0EzblH65130r8DcKkuAVMgric

{
  "title": "My First Blog",
  "author": "John Doe",
  "url": "https://example.com",
  "likes": 5
}

### Delete a blog by ID
DELETE http://localhost:3003/api/blogs/67e98236694891b3adbfb2db
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1c2luZW4iLCJpZCI6IjY3ZDNlZGU4ZTk2MDI5YmM5ZmU2ZDVjNyIsImlhdCI6MTc0MzM1NjQ0MywiZXhwIjoxNzQzMzYwMDQzfQ.u2v9KTZJHF6s8jtzDH0EzblH65130r8DcKkuAVMgric

### Update a blog by ID
PUT http://localhost:3003/api/blogs/67c4af7e2f78b1f510fa4023
Content-Type: application/json

{
  "title": "Updated Blog Title",
  "author": "John Doe",
  "url": "https://example.com",
  "likes": 10
}

### Get a non-existing blog (should return 404)
GET http://localhost:3003/api/blogs/000000000000000000000000
Accept: application/json

### Successful user creation
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "susinen",
  "name": "Roman Volkov",
  "password": "securepassword"
}

### Retrieve all users
GET http://localhost:3003/api/users
Accept: application/json

### Login
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "susinen",
  "password": "securepassword"
}
